### ISSUE TITLE
Line spacing in Tiro Devanagari fonts

### ISSUE THREAD

**Issue by Etewilak** [TiroTypeworks/Indigo#16]
With line spacing set at 1 in LibreOffice Writer, the bottom parts of the following consonant conjuncts do not appear completely:
![image](https://user-images.githubusercontent.com/55674356/171632414-50842c57-3d4e-46fa-a550-de9392aaef53.png)
This affects all three Tiro Devanagari fonts (Hindi, Marathi, and Sanskrit).

**Comment by tiroj** [comment]
Closing.

Comments and decisions on this issue all in
https://github.com/TiroTypeworks/Indigo/issues/17
