### ISSUE TITLE
TELUGU LETTER RRRA ౚ should not have headstroke

### ISSUE THREAD

**Issue by sridatta1** [TiroTypeworks/Indigo#31]
ౚ currently contains headstroke in the font.
![image](https://user-images.githubusercontent.com/23263723/180655167-69f91810-aacf-49d1-84cb-11a53e4d40d9.png)
There should not be any headstroke in the letter
![image](https://user-images.githubusercontent.com/23263723/180655205-6b2525d1-1b10-450a-a63a-f081a4063ef3.png)
Link to Unicode proposal
https://unicode.org/L2/L2012/12016-telugu-rrra-proposal.pdf

**Comment by tiroj** [comment]
Thanks. Noted for fix in next update.

**Comment by tiroj** [comment]
Fixing this alongside high priority #53 fix.

**Comment by tiroj** [comment]
Pleased to report that this fix has now gone live in Google Fonts.
