### ISSUE TITLE
Tiro Telugu v1.53 update QA report

### ISSUE THREAD

**Issue by vv-monsalve** [TiroTypeworks/Indigo#54]
The following are the findings after a QA round on Tiro Telegu v1.53 under Fontbakery v0.8.10

- Apart from the reported fail regarding the new Latin Core glyphset we are requiring now, no other Fails are reported.

<details><summary>🔥 <b>FAIL:</b> Check Google Fonts glyph coverage. (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/glyph_coverage">com.google.fonts/check/glyph_coverage</a>)</summary><div>

>
>Google Fonts expects that fonts in its collection support at least the minimal set of characters defined in the `GF-latin-core` glyph-set.
>
* 🔥 **FAIL** Missing required codepoints:

	- 0x030B (COMBINING DOUBLE ACUTE ACCENT)

	- 0x02D9 (DOT ABOVE)

	- 0x0104 (LATIN CAPITAL LETTER A WITH OGONEK)

	- 0x0106 (LATIN CAPITAL LETTER C WITH ACUTE)

	- 0x010A (LATIN CAPITAL LETTER C WITH DOT ABOVE)

	- 0x010E (LATIN CAPITAL LETTER D WITH CARON)

	- 0x0110 (LATIN CAPITAL LETTER D WITH STROKE)

	- 0x011A (LATIN CAPITAL LETTER E WITH CARON)

	- 0x0116 (LATIN CAPITAL LETTER E WITH DOT ABOVE)

	- 0x0118 (LATIN CAPITAL LETTER E WITH OGONEK)

	- 0x011E (LATIN CAPITAL LETTER G WITH BREVE)

	- 0x0122 (LATIN CAPITAL LETTER G WITH CEDILLA)

	- 0x0126 (LATIN CAPITAL LETTER H WITH STROKE)

	- 0x0132 (LATIN CAPITAL LIGATURE IJ)

	- 0x0130 (LATIN CAPITAL LETTER I WITH DOT ABOVE)

	- 0x012E (LATIN CAPITAL LETTER I WITH OGONEK)

	- 0x0136 (LATIN CAPITAL LETTER K WITH CEDILLA)

	- 0x013D (LATIN CAPITAL LETTER L WITH CARON)

	- 0x013B (LATIN CAPITAL LETTER L WITH CEDILLA)

	- 0x0141 (LATIN CAPITAL LETTER L WITH STROKE)

	- 0x0143 (LATIN CAPITAL LETTER N WITH ACUTE)

	- 0x0147 (LATIN CAPITAL LETTER N WITH CARON)

	- 0x014A (LATIN CAPITAL LETTER ENG)

	- 0x0150 (LATIN CAPITAL LETTER O WITH DOUBLE ACUTE)

	- 0x0158 (LATIN CAPITAL LETTER R WITH CARON)

	- 0x0156 (LATIN CAPITAL LETTER R WITH CEDILLA)

	- 0x015E (LATIN CAPITAL LETTER S WITH CEDILLA)

	- 0x0218 (LATIN CAPITAL LETTER S WITH COMMA BELOW)

	- 0x0164 (LATIN CAPITAL LETTER T WITH CARON)

	- 0x021A (LATIN CAPITAL LETTER T WITH COMMA BELOW)

	- 0x0170 (LATIN CAPITAL LETTER U WITH DOUBLE ACUTE)

	- 0x0172 (LATIN CAPITAL LETTER U WITH OGONEK)

	- 0x016E (LATIN CAPITAL LETTER U WITH RING ABOVE)

	- 0x1E82 (LATIN CAPITAL LETTER W WITH ACUTE)

	- 0x0174 (LATIN CAPITAL LETTER W WITH CIRCUMFLEX)

	- 0x1E84 (LATIN CAPITAL LETTER W WITH DIAERESIS)

	- 0x1E80 (LATIN CAPITAL LETTER W WITH GRAVE)

	- 0x0176 (LATIN CAPITAL LETTER Y WITH CIRCUMFLEX)

	- 0x1EF2 (LATIN CAPITAL LETTER Y WITH GRAVE)

	- 0x017B (LATIN CAPITAL LETTER Z WITH DOT ABOVE)

	- 0x0105 (LATIN SMALL LETTER A WITH OGONEK)

	- 0x0107 (LATIN SMALL LETTER C WITH ACUTE)

	- 0x010B (LATIN SMALL LETTER C WITH DOT ABOVE)

	- 0x010F (LATIN SMALL LETTER D WITH CARON)

	- 0x0111 (LATIN SMALL LETTER D WITH STROKE)

	- 0x011B (LATIN SMALL LETTER E WITH CARON)

	- 0x0117 (LATIN SMALL LETTER E WITH DOT ABOVE)

	- 0x0119 (LATIN SMALL LETTER E WITH OGONEK)

	- 0x011F (LATIN SMALL LETTER G WITH BREVE)

	- 0x0123 (LATIN SMALL LETTER G WITH CEDILLA)

	- 0x0127 (LATIN SMALL LETTER H WITH STROKE)

	- 0x0133 (LATIN SMALL LIGATURE IJ)

	- 0x012F (LATIN SMALL LETTER I WITH OGONEK)

	- 0x0137 (LATIN SMALL LETTER K WITH CEDILLA)

	- 0x013E (LATIN SMALL LETTER L WITH CARON)

	- 0x013C (LATIN SMALL LETTER L WITH CEDILLA)

	- 0x0142 (LATIN SMALL LETTER L WITH STROKE)

	- 0x0144 (LATIN SMALL LETTER N WITH ACUTE)

	- 0x0148 (LATIN SMALL LETTER N WITH CARON)

	- 0x014B (LATIN SMALL LETTER ENG)

	- 0x0151 (LATIN SMALL LETTER O WITH DOUBLE ACUTE)

	- 0x0159 (LATIN SMALL LETTER R WITH CARON)

	- 0x0157 (LATIN SMALL LETTER R WITH CEDILLA)

	- 0x015F (LATIN SMALL LETTER S WITH CEDILLA)

	- 0x0219 (LATIN SMALL LETTER S WITH COMMA BELOW)

	- 0x0165 (LATIN SMALL LETTER T WITH CARON)

	- 0x021B (LATIN SMALL LETTER T WITH COMMA BELOW)

	- 0x0171 (LATIN SMALL LETTER U WITH DOUBLE ACUTE)

	- 0x0173 (LATIN SMALL LETTER U WITH OGONEK)

	- 0x016F (LATIN SMALL LETTER U WITH RING ABOVE)

	- 0x1E83 (LATIN SMALL LETTER W WITH ACUTE)

	- 0x0175 (LATIN SMALL LETTER W WITH CIRCUMFLEX)

	- 0x1E85 (LATIN SMALL LETTER W WITH DIAERESIS)

	- 0x1E81 (LATIN SMALL LETTER W WITH GRAVE)

	- 0x0177 (LATIN SMALL LETTER Y WITH CIRCUMFLEX)

	- 0x1EF3 (LATIN SMALL LETTER Y WITH GRAVE)

	- 0x017C (LATIN SMALL LETTER Z WITH DOT ABOVE)

	- 0x0312 (COMBINING TURNED COMMA ABOVE)

	- 0x0328 (COMBINING OGONEK)

	- 0x02DD (DOUBLE ACUTE ACCENT)

	- 0x02C7 (CARON)

	- 0x02D8 (BREVE)
 

	- And 0x02DB (OGONEK)
 [code: missing-codepoints]
</div></details>

- There is a FB Warning about three glyphs that it detects are changing a lot from the previous version, but I think it would be an expected result after the fixes.

<details><summary>⚠ <b>WARN:</b> Glyphs are similiar to Google Fonts version? (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/production_glyphs_similarity">com.google.fonts/check/production_glyphs_similarity</a>)</summary><div>

* ⚠ **WARN** Following glyphs differ greatly from Google Fonts version:
	* tCai
	* tRrra
	* tRrru and tRrruu
</div></details>

- Running the Diffenator checks only report changes on a couple of Telugu words, but after looking for them in other Telugu fonts, they also seem ok

![qaTelugu-03-words](https://user-images.githubusercontent.com/48698976/211694217-bbea2a38-6117-4c8a-a5da-26e948dbd07a.gif)

If you confirm all the reports above are ok, I think it is ready for the PR to GF. Please remember that there could be other upper-level findings when creating the report, but I wouldn't expect anything crucial to happen.

**Comment by tiroj** [comment]
Confirmed: these are the expected changes.
