### ISSUE TITLE
Tiro Gurmukhi - FB report

### ISSUE THREAD

**Issue by vv-monsalve** [TiroTypeworks/Indigo#8]
Hi @tiroj, this is the FB report for the `v1.51` Tiro Gurmukhi fonts

The Warns reported seem to be the expected ones. Placing the report here in case you would like to double-check.

## Fontbakery report

Fontbakery version: 0.8.7

<details><summary><b>[9] TiroGurmukhi-Italic.ttf</b></summary><div><details><summary>⚠ <b>WARN:</b> Ensure Stylistic Sets have description.</summary><div>
* [com.google.fonts/check/stylisticset_description](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/stylisticset_description)
<pre>--- Rationale ---
Stylistic sets should provide description text. Programs such as InDesign,
TextEdit and Inkscape use that info to display to the users so that they know
what a given stylistic set offers.</pre>

* ⚠ **WARN** The stylistic set ss01 lacks a description string on the 'name' table. [code: missing-description]
* ⚠ **WARN** The stylistic set ss01 lacks a description string on the 'name' table. [code: missing-description]
* ⚠ **WARN** The stylistic set ss02 lacks a description string on the 'name' table. [code: missing-description]
* ⚠ **WARN** The stylistic set ss02 lacks a description string on the 'name' table. [code: missing-description]
* ⚠ **WARN** The stylistic set ss05 lacks a description string on the 'name' table. [code: missing-description]
* ⚠ **WARN** The stylistic set ss05 lacks a description string on the 'name' table. [code: missing-description]
* ⚠ **WARN** The stylistic set ss14 lacks a description string on the 'name' table. [code: missing-description]
* ⚠ **WARN** The stylistic set ss14 lacks a description string on the 'name' table. [code: missing-description]
* ⚠ **WARN** The stylistic set ss15 lacks a description string on the 'name' table. [code: missing-description]
* ⚠ **WARN** The stylistic set ss15 lacks a description string on the 'name' table. [code: missing-description]
* ⚠ **WARN** The stylistic set ss16 lacks a description string on the 'name' table. [code: missing-description]
* ⚠ **WARN** The stylistic set ss16 lacks a description string on the 'name' table. [code: missing-description]
* ⚠ **WARN** The stylistic set ss17 lacks a description string on the 'name' table. [code: missing-description]
* ⚠ **WARN** The stylistic set ss17 lacks a description string on the 'name' table. [code: missing-description]
* ⚠ **WARN** The stylistic set ss18 lacks a description string on the 'name' table. [code: missing-description]
* ⚠ **WARN** The stylistic set ss18 lacks a description string on the 'name' table. [code: missing-description]
* ⚠ **WARN** The stylistic set ss19 lacks a description string on the 'name' table. [code: missing-description]
* ⚠ **WARN** The stylistic set ss19 lacks a description string on the 'name' table. [code: missing-description]
* ⚠ **WARN** The stylistic set ss20 lacks a description string on the 'name' table. [code: missing-description]
* ⚠ **WARN** The stylistic set ss20 lacks a description string on the 'name' table. [code: missing-description]
</div></details><details><summary>⚠ <b>WARN:</b> Ensure fonts have ScriptLangTags declared on the 'meta' table.</summary><div>
* [com.google.fonts/check/meta/script_lang_tags](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/meta/script_lang_tags)
<pre>--- Rationale ---
The OpenType &#x27;meta&#x27; table originated at Apple. Microsoft added it to OT with
just two DataMap records:
- dlng: comma-separated ScriptLangTags that indicate which scripts, or languages
and scripts, with possible variants, the font is designed for
- slng: comma-separated ScriptLangTags that indicate which scripts, or languages
and scripts, with possible variants, the font supports
The slng structure is intended to describe which languages and scripts the font
overall supports. For example, a Traditional Chinese font that also contains
Latin characters, can indicate Hant,Latn, showing that it supports Hant, the
Traditional Chinese variant of the Hani script, and it also supports the Latn
script
The dlng structure is far more interesting. A font may contain various glyphs,
but only a particular subset of the glyphs may be truly &quot;leading&quot; in the design,
while other glyphs may have been included for technical reasons. Such a
Traditional Chinese font could only list Hant there, showing that it’s designed
for Traditional Chinese, but the font would omit Latn, because the developers
don’t think the font is really recommended for purely Latin-script use.
The tags used in the structures can comprise just script, or also language and
script. For example, if a font has Bulgarian Cyrillic alternates in the locl
feature for the cyrl BGR OT languagesystem, it could also indicate in dlng
explicitly that it supports bul-Cyrl. (Note that the scripts and languages in
meta use the ISO language and script codes, not the OpenType ones).
This check ensures that the font has the meta table containing the slng and dlng
structures.
All families in the Google Fonts collection should contain the &#x27;meta&#x27; table.
Windows 10 already uses it when deciding on which fonts to fall back to. The
Google Fonts API and also other environments could use the data for smarter
filtering. Most importantly, those entries should be added to the Noto fonts.
In the font making process, some environments store this data in external files
already. But the meta table provides a convenient way to store this inside the
font file, so some tools may add the data, and unrelated tools may read this
data. This makes the solution much more portable and universal.</pre>

* ⚠ **WARN** This font file does not have a 'meta' table. [code: lacks-meta-table]
</div></details><details><summary>⚠ <b>WARN:</b> Font has **proper** whitespace glyph names?</summary><div>
* [com.google.fonts/check/whitespace_glyphnames](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/universal.html#com.google.fonts/check/whitespace_glyphnames)
<pre>--- Rationale ---
This check enforces adherence to recommended whitespace (codepoints 0020 and
00A0) glyph names according to the Adobe Glyph List.</pre>

* ⚠ **WARN** Glyph 0x00A0 is called "nbspace": Change to "uni00A0" [code: not-recommended-00a0]
</div></details><details><summary>⚠ <b>WARN:</b> Glyph names are all valid?</summary><div>
* [com.google.fonts/check/valid_glyphnames](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/universal.html#com.google.fonts/check/valid_glyphnames)
<pre>--- Rationale ---
Microsoft&#x27;s recommendations for OpenType Fonts states the following:
&#x27;NOTE: The PostScript glyph name must be no longer than 31 characters, include
only uppercase or lowercase English letters, European digits, the period or the
underscore, i.e. from the set [A-Za-z0-9_.] and should start with a letter,
except the special glyph name &quot;.notdef&quot; which starts with a period.&#x27;
https://docs.microsoft.com/en-us/typography/opentype/spec/recom#post-table
In practice, though, particularly in modern environments, glyph names can be as
long as 63 characters.
According to the &quot;Adobe Glyph List Specification&quot; available at:
https://github.com/adobe-type-tools/agl-specification</pre>

* ⚠ **WARN** The following glyph names may be too long for some legacy systems which may expect a maximum 31-char length limit:
L_ringbelowcomb_macroncomb_acutecomb, R_ringbelowcomb_macroncomb_acutecomb, l_ringbelowcomb_macroncomb_acutecomb, r_ringbelowcomb_macroncomb_acutecomb, L_ringbelowcomb_macroncomb_acutecomb.sc, R_ringbelowcomb_macroncomb_acutecomb.sc, G_macronbelowcomb_H_macronbelowcomb and G_macronbelowcomb_H_macronbelowcomb.sc [code: legacy-long-names]
</div></details><details><summary>⚠ <b>WARN:</b> Check if each glyph has the recommended amount of contours.</summary><div>
* [com.google.fonts/check/contour_count](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/universal.html#com.google.fonts/check/contour_count)
<pre>--- Rationale ---
Visually QAing thousands of glyphs by hand is tiring. Most glyphs can only be
constructured in a handful of ways. This means a glyph&#x27;s contour count will only
differ slightly amongst different fonts, e.g a &#x27;g&#x27; could either be 2 or 3
contours, depending on whether its double story or single story.
However, a quotedbl should have 2 contours, unless the font belongs to a display
family.
This check currently does not cover variable fonts because there&#x27;s plenty of
alternative ways of constructing glyphs with multiple outlines for each feature
in a VarFont. The expected contour count data for this check is currently
optimized for the typical construction of glyphs in static fonts.</pre>

* ⚠ **WARN** This font has a 'Soft Hyphen' character (codepoint 0x00AD) which is supposed to be zero-width and invisible, and is used to mark a hyphenation possibility within a word in the absence of or overriding dictionary hyphenation. It is mostly an obsolete mechanism now, and the character is only included in fonts for legacy codepage coverage. [code: softhyphen]
* ⚠ **WARN** This check inspects the glyph outlines and detects the total number of contours in each of them. The expected values are infered from the typical ammounts of contours observed in a large collection of reference font families. The divergences listed below may simply indicate a significantly different design on some of your glyphs. On the other hand, some of these may flag actual bugs in the font such as glyphs mapped to an incorrect codepoint. Please consider reviewing the design and codepoint assignment of these to make sure they are correct.

The following glyphs do not have the recommended number of contours:

	- Glyph name: rupee	Contours detected: 1	Expected: 3
 [code: contour-count]
</div></details><details><summary>⚠ <b>WARN:</b> Checking Vertical Metric Linegaps.</summary><div>
* [com.google.fonts/check/linegaps](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/hhea.html#com.google.fonts/check/linegaps)

* ⚠ **WARN** hhea lineGap is not equal to 0. [code: hhea]
</div></details><details><summary>⚠ <b>WARN:</b> Check mark characters are in GDEF mark glyph class.</summary><div>
* [com.google.fonts/check/gdef_mark_chars](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/gdef.html#com.google.fonts/check/gdef_mark_chars)
<pre>--- Rationale ---
Mark characters should be in the GDEF mark glyph class.</pre>

* ⚠ **WARN** The following mark characters could be in the GDEF mark glyph class:
	 acutecomb (U+0301), brevebelowcomb (U+032E), brevecomb (U+0306), candrabinducomb (U+0310), caroncomb (U+030C), cedillacomb (U+0327), circumflexcomb (U+0302), commaaccentcomb (U+0326), dieresisbelowcomb (U+0324), dieresiscomb (U+0308), dotaccentcomb (U+0307), dotbelowcomb (U+0323), gravecomb (U+0300), macronbelowcomb (U+0331), macroncomb (U+0304), macrondblbelowcomb (U+035F), ringbelowcomb (U+0325), ringcomb (U+030A) and tildecomb (U+0303) [code: mark-chars]
</div></details><details><summary>⚠ <b>WARN:</b> Do any segments have colinear vectors?</summary><div>
* [com.google.fonts/check/outline_colinear_vectors](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/<Section: Outline Correctness Checks>.html#com.google.fonts/check/outline_colinear_vectors)
<pre>--- Rationale ---
This check looks for consecutive line segments which have the same angle. This
normally happens if an outline point has been added by accident.
This check is not run for variable fonts, as they may legitimately have colinear
vectors.</pre>

* ⚠ **WARN** The following glyphs have colinear vectors:
	* b (U+0062): L<<250.0,565.0>--<221.0,424.0>> -> L<<221.0,424.0>--<206.0,364.0>>
	* h (U+0068): L<<250.0,565.0>--<218.0,413.0>> -> L<<218.0,413.0>--<202.0,345.0>>
	* hdotbelow (U+1E25): L<<255.0,565.0>--<223.0,413.0>> -> L<<223.0,413.0>--<207.0,345.0>>
	* hlinebelow (U+1E96): L<<255.0,565.0>--<223.0,413.0>> -> L<<223.0,413.0>--<207.0,345.0>>
	* k (U+006B): L<<179.0,207.0>--<178.0,203.0>> -> L<<178.0,203.0>--<136.0,0.0>>
	* k (U+006B): L<<252.0,565.0>--<221.0,415.0>> -> L<<221.0,415.0>--<202.0,337.0>>
	* kdotbelow (U+1E33): L<<182.0,207.0>--<181.0,203.0>> -> L<<181.0,203.0>--<139.0,0.0>>
	* kdotbelow (U+1E33): L<<255.0,565.0>--<224.0,415.0>> -> L<<224.0,415.0>--<205.0,337.0>>
	* klinebelow (U+1E35): L<<182.0,207.0>--<181.0,203.0>> -> L<<181.0,203.0>--<139.0,0.0>>
	* klinebelow (U+1E35): L<<255.0,565.0>--<224.0,415.0>> -> L<<224.0,415.0>--<205.0,337.0>>
	* n (U+006E): L<<193.0,190.0>--<191.0,182.0>> -> L<<191.0,182.0>--<149.0,0.0>>
	* ncommaaccent (U+0146): L<<193.0,190.0>--<191.0,182.0>> -> L<<191.0,182.0>--<149.0,0.0>>
	* ndotaccent (U+1E45): L<<193.0,190.0>--<191.0,182.0>> -> L<<191.0,182.0>--<149.0,0.0>>
	* ndotbelow (U+1E47): L<<193.0,190.0>--<191.0,182.0>> -> L<<191.0,182.0>--<149.0,0.0>>
	* nmacronbelow (U+1E49): L<<193.0,190.0>--<191.0,182.0>> -> L<<191.0,182.0>--<149.0,0.0>>
	* ntilde (U+00F1): L<<193.0,190.0>--<191.0,182.0>> -> L<<191.0,182.0>--<149.0,0.0>>
	* q (U+0071): L<<355.0,297.0>--<358.0,309.0>> -> L<<358.0,309.0>--<378.0,393.0>> and thorn (U+00FE): L<<256.0,565.0>--<226.0,420.0>> -> L<<226.0,420.0>--<214.0,365.0>> [code: found-colinear-vectors]
</div></details><details><summary>⚠ <b>WARN:</b> Do outlines contain any jaggy segments?</summary><div>
* [com.google.fonts/check/outline_jaggy_segments](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/<Section: Outline Correctness Checks>.html#com.google.fonts/check/outline_jaggy_segments)
<pre>--- Rationale ---
This check heuristically detects outline segments which form a particularly
small angle, indicative of an outline error. This may cause false positives in
cases such as extreme ink traps, so should be regarded as advisory and backed up
by manual inspection.</pre>

* ⚠ **WARN** The following glyphs have jaggy segments:
	* g.Ai (U+0A10): B<<610.5,720.5>-<642.0,689.0>-<676.0,630.0>>/B<<676.0,630.0>-<651.0,712.0>-<629.5,758.0>> = 12.998295115776253 and g.SignAi (U+0A48): B<<-130.5,720.5>-<-99.0,689.0>-<-65.0,630.0>>/B<<-65.0,630.0>-<-90.0,712.0>-<-111.5,758.0>> = 12.998295115776253 [code: found-jaggy-segments]
</div></details><br></div></details><details><summary><b>[9] TiroGurmukhi-Regular.ttf</b></summary><div><details><summary>⚠ <b>WARN:</b> Ensure Stylistic Sets have description.</summary><div>
* [com.google.fonts/check/stylisticset_description](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/stylisticset_description)
<pre>--- Rationale ---
Stylistic sets should provide description text. Programs such as InDesign,
TextEdit and Inkscape use that info to display to the users so that they know
what a given stylistic set offers.</pre>

* ⚠ **WARN** The stylistic set ss01 lacks a description string on the 'name' table. [code: missing-description]
* ⚠ **WARN** The stylistic set ss01 lacks a description string on the 'name' table. [code: missing-description]
* ⚠ **WARN** The stylistic set ss02 lacks a description string on the 'name' table. [code: missing-description]
* ⚠ **WARN** The stylistic set ss02 lacks a description string on the 'name' table. [code: missing-description]
* ⚠ **WARN** The stylistic set ss05 lacks a description string on the 'name' table. [code: missing-description]
* ⚠ **WARN** The stylistic set ss05 lacks a description string on the 'name' table. [code: missing-description]
* ⚠ **WARN** The stylistic set ss14 lacks a description string on the 'name' table. [code: missing-description]
* ⚠ **WARN** The stylistic set ss14 lacks a description string on the 'name' table. [code: missing-description]
* ⚠ **WARN** The stylistic set ss15 lacks a description string on the 'name' table. [code: missing-description]
* ⚠ **WARN** The stylistic set ss15 lacks a description string on the 'name' table. [code: missing-description]
* ⚠ **WARN** The stylistic set ss16 lacks a description string on the 'name' table. [code: missing-description]
* ⚠ **WARN** The stylistic set ss16 lacks a description string on the 'name' table. [code: missing-description]
* ⚠ **WARN** The stylistic set ss17 lacks a description string on the 'name' table. [code: missing-description]
* ⚠ **WARN** The stylistic set ss17 lacks a description string on the 'name' table. [code: missing-description]
* ⚠ **WARN** The stylistic set ss18 lacks a description string on the 'name' table. [code: missing-description]
* ⚠ **WARN** The stylistic set ss18 lacks a description string on the 'name' table. [code: missing-description]
* ⚠ **WARN** The stylistic set ss19 lacks a description string on the 'name' table. [code: missing-description]
* ⚠ **WARN** The stylistic set ss19 lacks a description string on the 'name' table. [code: missing-description]
* ⚠ **WARN** The stylistic set ss20 lacks a description string on the 'name' table. [code: missing-description]
* ⚠ **WARN** The stylistic set ss20 lacks a description string on the 'name' table. [code: missing-description]
</div></details><details><summary>⚠ <b>WARN:</b> Ensure fonts have ScriptLangTags declared on the 'meta' table.</summary><div>
* [com.google.fonts/check/meta/script_lang_tags](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/meta/script_lang_tags)
<pre>--- Rationale ---
The OpenType &#x27;meta&#x27; table originated at Apple. Microsoft added it to OT with
just two DataMap records:
- dlng: comma-separated ScriptLangTags that indicate which scripts, or languages
and scripts, with possible variants, the font is designed for
- slng: comma-separated ScriptLangTags that indicate which scripts, or languages
and scripts, with possible variants, the font supports
The slng structure is intended to describe which languages and scripts the font
overall supports. For example, a Traditional Chinese font that also contains
Latin characters, can indicate Hant,Latn, showing that it supports Hant, the
Traditional Chinese variant of the Hani script, and it also supports the Latn
script
The dlng structure is far more interesting. A font may contain various glyphs,
but only a particular subset of the glyphs may be truly &quot;leading&quot; in the design,
while other glyphs may have been included for technical reasons. Such a
Traditional Chinese font could only list Hant there, showing that it’s designed
for Traditional Chinese, but the font would omit Latn, because the developers
don’t think the font is really recommended for purely Latin-script use.
The tags used in the structures can comprise just script, or also language and
script. For example, if a font has Bulgarian Cyrillic alternates in the locl
feature for the cyrl BGR OT languagesystem, it could also indicate in dlng
explicitly that it supports bul-Cyrl. (Note that the scripts and languages in
meta use the ISO language and script codes, not the OpenType ones).
This check ensures that the font has the meta table containing the slng and dlng
structures.
All families in the Google Fonts collection should contain the &#x27;meta&#x27; table.
Windows 10 already uses it when deciding on which fonts to fall back to. The
Google Fonts API and also other environments could use the data for smarter
filtering. Most importantly, those entries should be added to the Noto fonts.
In the font making process, some environments store this data in external files
already. But the meta table provides a convenient way to store this inside the
font file, so some tools may add the data, and unrelated tools may read this
data. This makes the solution much more portable and universal.</pre>

* ⚠ **WARN** This font file does not have a 'meta' table. [code: lacks-meta-table]
</div></details><details><summary>⚠ <b>WARN:</b> Font has **proper** whitespace glyph names?</summary><div>
* [com.google.fonts/check/whitespace_glyphnames](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/universal.html#com.google.fonts/check/whitespace_glyphnames)
<pre>--- Rationale ---
This check enforces adherence to recommended whitespace (codepoints 0020 and
00A0) glyph names according to the Adobe Glyph List.</pre>

* ⚠ **WARN** Glyph 0x00A0 is called "nbspace": Change to "uni00A0" [code: not-recommended-00a0]
</div></details><details><summary>⚠ <b>WARN:</b> Glyph names are all valid?</summary><div>
* [com.google.fonts/check/valid_glyphnames](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/universal.html#com.google.fonts/check/valid_glyphnames)
<pre>--- Rationale ---
Microsoft&#x27;s recommendations for OpenType Fonts states the following:
&#x27;NOTE: The PostScript glyph name must be no longer than 31 characters, include
only uppercase or lowercase English letters, European digits, the period or the
underscore, i.e. from the set [A-Za-z0-9_.] and should start with a letter,
except the special glyph name &quot;.notdef&quot; which starts with a period.&#x27;
https://docs.microsoft.com/en-us/typography/opentype/spec/recom#post-table
In practice, though, particularly in modern environments, glyph names can be as
long as 63 characters.
According to the &quot;Adobe Glyph List Specification&quot; available at:
https://github.com/adobe-type-tools/agl-specification</pre>

* ⚠ **WARN** The following glyph names may be too long for some legacy systems which may expect a maximum 31-char length limit:
L_ringbelowcomb_macroncomb_acutecomb, R_ringbelowcomb_macroncomb_acutecomb, l_ringbelowcomb_macroncomb_acutecomb, r_ringbelowcomb_macroncomb_acutecomb, L_ringbelowcomb_macroncomb_acutecomb.sc, R_ringbelowcomb_macroncomb_acutecomb.sc, G_macronbelowcomb_H_macronbelowcomb and G_macronbelowcomb_H_macronbelowcomb.sc [code: legacy-long-names]
</div></details><details><summary>⚠ <b>WARN:</b> Check if each glyph has the recommended amount of contours.</summary><div>
* [com.google.fonts/check/contour_count](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/universal.html#com.google.fonts/check/contour_count)
<pre>--- Rationale ---
Visually QAing thousands of glyphs by hand is tiring. Most glyphs can only be
constructured in a handful of ways. This means a glyph&#x27;s contour count will only
differ slightly amongst different fonts, e.g a &#x27;g&#x27; could either be 2 or 3
contours, depending on whether its double story or single story.
However, a quotedbl should have 2 contours, unless the font belongs to a display
family.
This check currently does not cover variable fonts because there&#x27;s plenty of
alternative ways of constructing glyphs with multiple outlines for each feature
in a VarFont. The expected contour count data for this check is currently
optimized for the typical construction of glyphs in static fonts.</pre>

* ⚠ **WARN** This font has a 'Soft Hyphen' character (codepoint 0x00AD) which is supposed to be zero-width and invisible, and is used to mark a hyphenation possibility within a word in the absence of or overriding dictionary hyphenation. It is mostly an obsolete mechanism now, and the character is only included in fonts for legacy codepage coverage. [code: softhyphen]
* ⚠ **WARN** This check inspects the glyph outlines and detects the total number of contours in each of them. The expected values are infered from the typical ammounts of contours observed in a large collection of reference font families. The divergences listed below may simply indicate a significantly different design on some of your glyphs. On the other hand, some of these may flag actual bugs in the font such as glyphs mapped to an incorrect codepoint. Please consider reviewing the design and codepoint assignment of these to make sure they are correct.

The following glyphs do not have the recommended number of contours:

	- Glyph name: rupee	Contours detected: 1	Expected: 3
 [code: contour-count]
</div></details><details><summary>⚠ <b>WARN:</b> Checking Vertical Metric Linegaps.</summary><div>
* [com.google.fonts/check/linegaps](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/hhea.html#com.google.fonts/check/linegaps)

* ⚠ **WARN** hhea lineGap is not equal to 0. [code: hhea]
</div></details><details><summary>⚠ <b>WARN:</b> Check mark characters are in GDEF mark glyph class.</summary><div>
* [com.google.fonts/check/gdef_mark_chars](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/gdef.html#com.google.fonts/check/gdef_mark_chars)
<pre>--- Rationale ---
Mark characters should be in the GDEF mark glyph class.</pre>

* ⚠ **WARN** The following mark characters could be in the GDEF mark glyph class:
	 acutecomb (U+0301), brevebelowcomb (U+032E), brevecomb (U+0306), candrabinducomb (U+0310), caroncomb (U+030C), cedillacomb (U+0327), circumflexcomb (U+0302), commaaccentcomb (U+0326), dieresisbelowcomb (U+0324), dieresiscomb (U+0308), dotaccentcomb (U+0307), dotbelowcomb (U+0323), gravecomb (U+0300), macronbelowcomb (U+0331), macroncomb (U+0304), macrondblbelowcomb (U+035F), ringbelowcomb (U+0325), ringcomb (U+030A) and tildecomb (U+0303) [code: mark-chars]
</div></details><details><summary>⚠ <b>WARN:</b> Do outlines contain any jaggy segments?</summary><div>
* [com.google.fonts/check/outline_jaggy_segments](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/<Section: Outline Correctness Checks>.html#com.google.fonts/check/outline_jaggy_segments)
<pre>--- Rationale ---
This check heuristically detects outline segments which form a particularly
small angle, indicative of an outline error. This may cause false positives in
cases such as extreme ink traps, so should be regarded as advisory and backed up
by manual inspection.</pre>

* ⚠ **WARN** The following glyphs have jaggy segments:
	* g.Ai (U+0A10): B<<522.0,721.0>-<557.0,689.0>-<601.0,631.0>>/B<<601.0,631.0>-<560.0,713.0>-<528.0,758.5>> = 10.61965527615507 and g.SignAi (U+0A48): B<<-219.0,721.0>-<-184.0,689.0>-<-140.0,631.0>>/B<<-140.0,631.0>-<-181.0,713.0>-<-213.0,758.5>> = 10.61965527615507 [code: found-jaggy-segments]
</div></details><details><summary>⚠ <b>WARN:</b> Do outlines contain any semi-vertical or semi-horizontal lines?</summary><div>
* [com.google.fonts/check/outline_semi_vertical](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/<Section: Outline Correctness Checks>.html#com.google.fonts/check/outline_semi_vertical)
<pre>--- Rationale ---
This check detects line segments which are nearly, but not quite, exactly
horizontal or vertical. Sometimes such lines are created by design, but often
they are indicative of a design error.
This check is disabled for italic styles, which often contain nearly-upright
lines.</pre>

* ⚠ **WARN** The following glyphs have semi-vertical/semi-horizontal lines:
 * fivesuperior (U+2075): L<<101.0,783.0>--<334.0,785.0>>
 * g.Ra (U+0A30): L<<378.0,400.0>--<377.0,542.0>> and g.Ra (U+0A30): L<<379.0,211.0>--<378.0,326.0>> [code: found-semi-vertical]
</div></details><br></div></details>
### Summary

| 💔 ERROR | 🔥 FAIL | ⚠ WARN | 💤 SKIP | ℹ INFO | 🍞 PASS | 🔎 DEBUG |
|:-----:|:----:|:----:|:----:|:----:|:----:|:----:|
| 0 | 0 | 18 | 218 | 15 | 179 | 0 |
| 0% | 0% | 4% | 51% | 3% | 42% | 0% |

**Note:** The following loglevels were omitted in this report:
* **SKIP**
* **INFO**
* **PASS**
* **DEBUG**

**Comment by tiroj** [comment]
v1.51

Warnings reviewed and confirmed as expected for this release: issues either features not implementable in current tool chain, by design, or harmless artifacts of outline merging.
